### ISSUE TITLE
server->Wait()

### ISSUE THREAD

**Issue by saddlekiller** [adamrehn/ue4-grpc-demo#6]
Hi~When I read GRPC tutorials, I found they call "server->Wait()" when starting a server, which is different from this repo. So, is there any reason that "Wait()" shouldn't be called here?

**Comment by adamrehn** [comment]
Presumably you figured this out when you closed the issue, but I'll post the answer here for future reference in case anyone else has this same question. The `Wait()` method will block the calling thread until the gRPC server finishes running, which makes sense in an application where you run the server from the main thread but is unnecessary (and actually undesirable) in an Unreal Engine application, where the server will be run from the game thread, which has its own event loop and should not be blocked.
